export const initialAccounts = [
  {
    id: 1,
    name: "Account 1",
    interestRate: "1.5%",
    type: "Savings",
    fee: "$5/month",
  },
  {
    id: 2,
    name: "Account 2",
    interestRate: "2.0%",
    type: "Checking",
    fee: "$0/month",
  },
  {
    id: 3,
    name: "Account 3",
    interestRate: "1.8%",
    type: "Savings",
    fee: "$10/month",
  },
  {
    id: 4,
    name: "Account 4",
    interestRate: "2.2%",
    type: "Checking",
    fee: "$0/month",
  },
  {
    id: 5,
    name: "Account 5",
    interestRate: "1.3%",
    type: "Savings",
    fee: "$4/month",
  },
  {
    id: 6,
    name: "Account 6",
    interestRate: "2.5%",
    type: "Checking",
    fee: "$0/month",
  },
  {
    id: 7,
    name: "Account 7",
    interestRate: "1.7%",
    type: "Savings",
    fee: "$6/month",
  },
  {
    id: 8,
    name: "Account 8",
    interestRate: "2.0%",
    type: "Checking",
    fee: "$0/month",
  },
  {
    id: 9,
    name: "Account 9",
    interestRate: "1.9%",
    type: "Savings",
    fee: "$7/month",
  },
  {
    id: 10,
    name: "Account 10",
    interestRate: "2.3%",
    type: "Checking",
    fee: "$0/month",
  },
  {
    id: 11,
    name: "Account 11",
    interestRate: "1.6%",
    type: "Savings",
    fee: "$8/month",
  },
  {
    id: 12,
    name: "Account 12",
    interestRate: "2.4%",
    type: "Checking",
    fee: "$0/month",
  },
  {
    id: 13,
    name: "Account 13",
    interestRate: "1.4%",
    type: "Savings",
    fee: "$9/month",
  },
  {
    id: 14,
    name: "Account 14",
    interestRate: "2.1%",
    type: "Checking",
    fee: "$0/month",
  },
  {
    id: 15,
    name: "Account 15",
    interestRate: "1.9%",
    type: "Savings",
    fee: "$5/month",
  },
];
