export const creditCards = [
  {
    cardName: "Liv - World Credit Card",
    imageUrl: "/mnt/data/image1.png",
    minimumSalary: "AED 10000",
    annualFee: "AED 700",
    rate: "3.09%",
    salaryTransfer: "No",
    features: [
      "Cash Back",
      "Discounts / Vouchers / Offers",
      "Balance Transfer",
      "Airport",
    ],
    applyLink: "https://example.com/apply-now-1",
  },
  {
    cardName: "Gold Credit Card",
    imageUrl: "/mnt/data/image2.png",
    minimumSalary: "AED 12000",
    annualFee: "AED 500",
    rate: "2.99%",
    salaryTransfer: "No",
    features: [
      "Cash Back",
      "Free Airport Lounge Access",
      "Travel Insurance",
      "Dining Offers",
    ],
    applyLink: "https://example.com/apply-now-2",
  },
  {
    cardName: "Platinum Credit Card",
    imageUrl: "/mnt/data/image3.png",
    minimumSalary: "AED 15000",
    annualFee: "AED 1000",
    rate: "2.89%",
    salaryTransfer: "Yes",
    features: [
      "Cash Back",
      "Online Shopping Discounts",
      "Movie Tickets Offers",
      "Bill Payments",
    ],
    applyLink: "https://example.com/apply-now-3",
  },
  {
    cardName: "Standard Credit Card",
    imageUrl: "/mnt/data/image4.png",
    minimumSalary: "AED 8000",
    annualFee: "AED 300",
    rate: "3.19%",
    salaryTransfer: "No",
    features: [
      "Cash Back",
      "Discounts / Vouchers / Offers",
      "Balance Transfer",
      "Bill Payments",
    ],
    applyLink: "https://example.com/apply-now-4",
  },
  {
    cardName: "Silver Credit Card",
    imageUrl: "/mnt/data/image5.png",
    minimumSalary: "AED 9000",
    annualFee: "AED 600",
    rate: "3.15%",
    salaryTransfer: "No",
    features: [
      "Cash Back",
      "Online Shopping Discounts",
      "Movie Tickets Offers",
      "Bill Payments",
    ],
    applyLink: "https://example.com/apply-now-5",
  },
  {
    cardName: "Black Credit Card",
    imageUrl: "/mnt/data/image6.png",
    minimumSalary: "AED 20000",
    annualFee: "AED 1500",
    rate: "2.75%",
    salaryTransfer: "Yes",
    features: [
      "Luxury Rewards",
      "Free Airport Lounge Access",
      "Travel Insurance",
      "Concierge Service",
    ],
    applyLink: "https://example.com/apply-now-6",
  },
  {
    cardName: "Titanium Credit Card",
    imageUrl: "/mnt/data/image7.png",
    minimumSalary: "AED 14000",
    annualFee: "AED 900",
    rate: "2.95%",
    salaryTransfer: "No",
    features: [
      "Cash Back",
      "Discounts / Vouchers / Offers",
      "Balance Transfer",
      "No Annual Fee for 1st Year",
    ],
    applyLink: "https://example.com/apply-now-7",
  },
  {
    cardName: "Titanium Credit Card",
    imageUrl: "/mnt/data/image8.png",
    minimumSalary: "AED 25000",
    annualFee: "AED 2000",
    rate: "2.50%",
    salaryTransfer: "Yes",
    features: [
      "Business Travel Insurance",
      "Corporate Discounts",
      "Higher Credit Limit",
      "Concierge Service",
    ],
    applyLink: "https://example.com/apply-now-8",
  },
  {
    cardName: "Business Credit Card",
    imageUrl: "/mnt/data/image9.png",
    minimumSalary: "AED 18000",
    annualFee: "AED 1200",
    rate: "2.85%",
    salaryTransfer: "Yes",
    features: [
      "Business Rewards",
      "Travel Insurance",
      "Dining Offers",
      "Cash Back",
    ],
    applyLink: "https://example.com/apply-now-9",
  },
  {
    cardName: "Liv - World Credit Card",
    imageUrl: "/mnt/data/image10.png",
    minimumSalary: "AED 5000",
    annualFee: "AED 200",
    rate: "3.25%",
    salaryTransfer: "No",
    features: [
      "Cash Back",
      "Discounts / Vouchers / Offers",
      "Balance Transfer",
      "No Annual Fee for 1st Year",
    ],
    applyLink: "https://example.com/apply-now-10",
  },
  {
    cardName: "Premium Credit Card",
    imageUrl: "/mnt/data/image11.png",
    minimumSalary: "AED 22000",
    annualFee: "AED 1800",
    rate: "2.70%",
    salaryTransfer: "Yes",
    features: [
      "Luxury Rewards",
      "Free Airport Lounge Access",
      "Travel Insurance",
      "Exclusive Offers",
    ],
    applyLink: "https://example.com/apply-now-11",
  },
  {
    cardName: "Business Credit Card",
    imageUrl: "/mnt/data/image12.png",
    minimumSalary: "AED 11000",
    annualFee: "AED 750",
    rate: "3.05%",
    salaryTransfer: "No",
    features: [
      "Rewards Points",
      "Discounts / Vouchers / Offers",
      "Balance Transfer",
      "Dining Offers",
    ],
    applyLink: "https://example.com/apply-now-12",
  },
  {
    cardName: "Travel Credit Card",
    imageUrl: "/mnt/data/image13.png",
    minimumSalary: "AED 13000",
    annualFee: "AED 850",
    rate: "3.00%",
    salaryTransfer: "No",
    features: [
      "Travel Insurance",
      "Free Airport Lounge Access",
      "Travel Discounts",
      "Concierge Service",
    ],
    applyLink: "https://example.com/apply-now-13",
  },
  {
    cardName: "Premium Credit Card",
    imageUrl: "/mnt/data/image14.png",
    minimumSalary: "AED 16000",
    annualFee: "AED 950",
    rate: "2.85%",
    salaryTransfer: "Yes",
    features: [
      "Business Rewards",
      "Travel Insurance",
      "Dining Offers",
      "Cash Back",
    ],
    applyLink: "https://example.com/apply-now-14",
  },
];

export const typesOfCards = [
  "Liv - World Credit Card",
  "Gold Credit Card",
  "Platinum Credit Card",
  "Standard Credit Card",
  "Silver Credit Card",
  "Black Credit Card",
  "Titanium Credit Card",
  "Business Credit Card",
  "Premium Credit Card",
  "Travel Credit Card",
];

export const Features = [
  "Travel Discounts",
  "Concierge Service",
  "Luxury Rewards",
  "Free Airport Lounge Access",
  "Exclusive Offers",
  "Cash Back",
  "Discounts / Vouchers / Offers",
  "Balance Transfer",
  "No Annual Fee for 1st Year",
  "Business Rewards",
  "Travel Insurance",
  "Dining Offers",
  "Online Shopping Discounts",
  "Movie Tickets Offers",
  "Bill Payments",
];
